[Query]
add_data = INSERT INTO signup (name, username, email, password,age,city, state, country, pin) VALUES ('$name' , '$username', '$email', '$password','$age', '$city', '$state', '$country', '$pin')
fetch_username = select username, password from signup where username = '$username' and password = '$password'
add_event = INSERT INTO event (username ,artist_name, "Date", location , city, country) VALUES ('$username', '$artist_name' , '$date', '$location', '$city','$country')
fetch_all_filter = SELECT signup.username, signup.Name, signup.City, signup.Country, event.username, event.City, event.Country, event.location, "Uploadimage"."profilePicture" FROM signup RIGHT JOIN event ON signup.username = event.username LEFT JOIN "Uploadimage" ON event.username = "Uploadimage".username WHERE LOWER(event.City) = '$city' AND LOWER(event.Country) = '$country';
#fetch_user_data = SELECT  name,city,country,age,about from signup where username = '$username'
fetch_user_data = SELECT s.name, s.city, s.country, s.age, s.about, u."profilePicture" FROM signup AS s LEFT JOIN "Uploadimage" AS u ON s.username = u.username WHERE s.username = '$username'
update_about_me_data = UPDATE signup SET about = '$about' WHERE username = '$username';
update_age_data = UPDATE signup SET age = '$age' WHERE username = '$username';
update_age_city = UPDATE signup SET city = '$city' WHERE username = '$username';
update_age_country = UPDATE signup SET country = '$country' WHERE username = '$username';
upload_pic = INSERT INTO "Uploadimage" (username, "profilePicture") VALUES (%%s, %%s) ON CONFLICT (username) DO UPDATE SET "profilePicture" = EXCLUDED."profilePicture";
#send_request = INSERT INTO Matches (username, receiver, messaage) VALUES ('$username', '$receiver', '$messaage')
send_request = INSERT INTO Matches (username, receiver, messaage) VALUES (%%s, %%s, %%s)
matches_data = SELECT DISTINCT r.username AS Username, r.name AS Name, r.Age AS Age FROM Matches m JOIN signup r ON m.username = r.username WHERE m.status = 2 AND m.receiver = '$username';
decline_matches = UPDATE Matches SET status = 0 WHERE receiver = '$username' AND username = '$receiver';



